name: Pull and Run Container

on:
  push:
    branches:
      - action


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONCENT_DB_URL: ${{ secrets.CONCENT_DB_URL }}
      DRIVER_CLASS: ${{ secrets.DRIVER_CLASS }}
      CONCENT_USERNAME: ${{ secrets.CONCENT_USERNAME }}
      CONCENT_PASSWORD: ${{ secrets.CONCENT_PASSWORD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
      PORT: ${{ secrets.PORT }}
      S3_BASE_URL: ${{ secrets.S3_BASE_URL }}



    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up environment variables
        run: |
            echo "CONCENT_DB_URL=${{ env.CONCENT_DB_URL }}" >> $GITHUB_ENV
            echo "DRIVER_CLASS=${{ env.DRIVER_CLASS }}" >> $GITHUB_ENV
            echo "CONCENT_USERNAME=${{ env.CONCENT_USERNAME }}" >> $GITHUB_ENV
            echo "CONCENT_PASSWORD=${{ env.CONCENT_PASSWORD }}" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY=${{ env.AWS_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "AWS_SECRET_KEY=${{ env.AWS_SECRET_KEY }}" >> $GITHUB_ENV
            echo "S3_BUCKET_NAME=${{ env.S3_BUCKET_NAME }}" >> $GITHUB_ENV
            echo "AWS_S3_REGION=${{ env.AWS_S3_REGION }}" >> $GITHUB_ENV
            echo "PORT=${{ env.PORT }}" >> $GITHUB_ENV
            echo "S3_BASE_URL=${{ env.S3_BASE_URL }}" >> $GITHUB_ENV

      - name: Build and push
        run:
          ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: concent/sfl:1.22
          platforms: linux/amd64,linux/arm64,linux/arm/v7