name: Docker

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CONCENT_DB_URL: ${{ secrets.CONCENT_DB_URL }}
      DRIVER_CLASS: ${{ secrets.DRIVER_CLASS }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
      PORT: ${{ secrets.PORT }}
      S3_BASE_URL: ${{ secrets.S3_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate env Parameter
        run: |
          echo "CONCENT_DB_URL=$CONCENT_DB_URL" >> .env.local
          echo "DRIVER_CLASS=$DRIVER_CLASS" >> .env.local
          echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" >> .env.local
          echo "AWS_SECRET_KEY=$AWS_SECRET_KEY" >> .env.local
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> .env.local
          echo "AWS_S3_REGION=$AWS_S3_REGION" >> .env.local
          echo "PORT=$PORT" >> .env.local
          echo "S3_BASE_URL=$S3_BASE_URL" >> .env.local

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: concent/sfl:1.21
          platforms: linux/amd64,linux/arm64,linux/arm/v7