name: Pull and Run Container

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1



      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        run:
          ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: concent/sfl:1.21
          platforms: linux/amd64,linux/arm64,linux/arm/v7